-- Create restaurants table
create table restaurants (
  id bigint generated by default as identity primary key,
  name text not null unique,
  google_place_id text unique,
  website text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create reviews table
create table reviews (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references restaurants(id) not null,
  user_name text not null,
  rating numeric(2, 1) not null, -- Allows 0.5 increments, e.g., 4.5
  review text, -- Renamed from comment
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
